### ISSUE TITLE
Bradesco com informação de protesto

### ISSUE THREAD

**Issue by giorgiootto** [mundipagg/boleto-api#189]
Ola,

Consigo registrar boletos no Bradesco com informação de que deve ser protesto????

E a a criação de boleto em PDF já esta funcionando????

Att.
Giorgio

**Comment by vpecanha** [comment]
@giorgiootto  Tudo bem?
Ainda não temos isto no roadmap e não temos previsão de adicionar. Isto também serve para conversão em PDF.
