### ISSUE TITLE
SEQ Keys

### ISSUE THREAD

**Issue by mccraveiro** [mundipagg/boleto-api#3]
There are seq keys in the source code and on the commit history. Is this secure?

**Comment by mccraveiro** [comment]
@agaldino The Git history should be rewriten to remove these keys as they can still be seen on github. They should also be invalidated on the server.

**Comment by greenboxal** [comment]
I don't think you need to rewrite the commit history as long as you invalidate the key on the server.

**Comment by agaldino** [comment]
@mccraveiro @greenboxal At the time I close this issue, I've also invalidated the key on the server.

**Comment by mccraveiro** [comment]
Nice! 👏
