### ISSUE TITLE
Banco Bradesco

### ISSUE THREAD

**Issue by giorgiootto** [mundipagg/boleto-api#70]
Boas,

Tem alguma idéia quando vai suportar o B.Bradesco???? Safra???

**Comment by PMoneda** [comment]
Olá!
O banco Bradesco já está em desenvolvimento/homologação o banco Safra ainda sem previsão.

**Comment by giorgiootto** [comment]
OK. Obrigado 

    Em Quinta-feira, 14 de Setembro de 2017 10:02, Phlippe Moneda <notifications@github.com> escreveu:
 

 Olá!
O banco Bradesco já está em desenvolvimento/homologação o banco Safra ainda sem previsão.—
