### ISSUE TITLE
Condições de IF utilizando atribuidores

### ISSUE THREAD

**Issue by rafa-acioly** [mundipagg/boleto-api#75]
Em alguns arquivos notei o seguinte uso dos `if statement` (exemplo que se encontra no [arquivo boleto](https://github.com/mundipagg/boleto-api/blob/master/api/boleto.go#L60)):

```go
errMongo := repo.SaveBoleto(boView)
if errMongo != nil {
    saveBoletoJSONFile(boView, lg, errMongo)
}
```

Os mesmos podem ser usados/comparados com uma atribuição de variável antes da comparação, deste modo:

```go
if errMongo := repo.SaveBoleto(boView); errMongo != nil {
    saveBoletoJSONFile(boView, lg, errMongo)
}
```

> Deste modo a variável `errMongo` só ficara disponível no escopo do `if` em que se encontra.

Existe algo que impeça isso ser alterado? versão do `Go`/Estilo do código.. ?
Me disponho a aplicar tais correções para que os arquivos tenham uma quantidade de linhas menores e para que possa ser usado a sintaxe disponibilizada pelo `Go`.

**Comment by PMoneda** [comment]
Olá, pode ajustar sim! Sua alterações serão bem vindas!
