### ISSUE TITLE
Overflow em campo "OurNumber"

### ISSUE THREAD

**Issue by rafa-acioly** [mundipagg/boleto-api#77]
Ao clonar o repositório e executar `go build` o seguinte erro é apresentado:

```
# github.com/mundipagg/boleto-api/bb
bb/validations.go:51:24: constant 9999999999 overflows uint
```
que diz respeito á uma [linha no arquivo de validations dentro do package bb](https://github.com/mundipagg/boleto-api/blob/master/bb/validations.go#L51)

o campo `OurNumber` esta definido apenas como `uint` [no arquivo title dentro do package models](https://github.com/mundipagg/boleto-api/blob/master/models/title.go#L17)

Para que este problema seja resolvido é necessário saber a quantidade de caracteres que um "OurNumber/Nosso Número" possui para então aplicar o tipo correto.
O erro apresentado diz respeito apenas a 1 digito, se removermos um `"9"` do arquivo `validations` o problema é resolvido, porém não sei quantos caracteres o `OurNumber ` utiliza para realizar a devida validação.

**Comment by leojasmim** [comment]
@rafa-acioly nos casos em que o OurNumber seja informado na requisição ele está limitado ao `uint64`, i.e., 18446744073709551615. Logo, é seguro assumir que ele possa ter, no máximo, 19 dígitos.
