### ISSUE TITLE
Manual Caixa

### ISSUE THREAD

**Issue by elvispdosreis** [mundipagg/boleto-api#88]
Eu procuro o manual de integração da caixa por webservice e contato da caixa para suporte, caso voce tenha pode me fornecer por favor

**Comment by loja5combr** [comment]
https://github.com/loja5combr/DevGuides/blob/master/38239%20leiaute%20webservice.doc

**Comment by elvispdosreis** [comment]
Obrigado

2017-10-28 11:56 GMT-02:00 Bruno Alencar <notifications@github.com>:

**Comment by riopardo** [comment]
Algum exemplo do Santander?

**Comment by hugocarreira** [comment]
@paulolimarb

**Comment by PMoneda** [comment]
@paulolimarb
